version: "2.0"

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     container_name: "${PROJECT_NAME}_jefe_nginx_proxy"
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro

   db:
     image: mysql:5.7
     container_name: "${PROJECT_NAME}_db"
     volumes:
       - db_data:/var/lib/mysql
     restart: on-failure
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: "wordpress:${WORDPRESS_VERSION}"
     container_name: "${PROJECT_NAME}_wordpress"
     volumes:
       - "${PROJECT_ROOT}:/var/www/html/wp-content"
     restart: on-failure
     environment:
       VIRTUAL_HOST: "${VHOST}"
       NGINX_PORT: "${NGINX_PORT}"
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"
       ENVIRONMENT: "${ENVIRONMENT}"

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: "${PROJECT_NAME}_phpmyadmin"
     depends_on:
       - db
     environment:
       PMA_HOST: db
       VIRTUAL_HOST: "phpmyadmin.${VHOST}"
volumes:
    db_data:
