version: '2'
services:
  <PROJECT_NAME>_php:
    image: 'jefecito/php:7.0-apache'
    container_name: '${PROJECT_NAME}_php'
    networks:
      - jefe-cli
    environment:
      VIRTUAL_HOST: '${VHOST}'
      DB_HOST: '<PROJECT_NAME>_mysql'
      DB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      ENVIRONMENT: '${ENVIRONMENT}'
    volumes:
      - '${PROJECT_ROOT}:/var/www/html'
    depends_on:
      - <PROJECT_NAME>_mysql
  <PROJECT_NAME>_mysql:
    image: 'mysql:latest'
    container_name: '${PROJECT_NAME}_db'
    networks:
      - jefe-cli
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
volumes:
  db_data: null
networks:
  jefe-cli:
    external:
      name: jefe-cli
