version: '2'
services:
  <PROJECT_NAME>_nginx:
    image: 'jefecito/nginx:php-fpm'
    container_name: '${PROJECT_NAME}_nginx'
    networks:
      - jefe-cli
    environment:
      VIRTUAL_HOST: '${VHOST}'
      ROOT: '${DOCUMENT_ROOT}'
      UPSTREAM: '<PROJECT_NAME>_php'
    volumes:
      - '${PROJECT_ROOT}:/var/www/html'
    depends_on:
      - <PROJECT_NAME>_php
  <PROJECT_NAME>_php:
    image: 'jefecito/php:7.0-fpm'
    hostname: '${PROJECT_NAME}_php'
    container_name: '${PROJECT_NAME}_php'
    networks:
      - jefe-cli
    environment:
      DB_HOST: '<PROJECT_NAME>_mysql'
      DB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      ENVIRONMENT: '${ENVIRONMENT}'
    expose:
      - 9000
    volumes:
      - '${PROJECT_ROOT}:/var/www/html'
    depends_on:
      - <PROJECT_NAME>_mysql
  <PROJECT_NAME>_mysql:
    image: 'mysql:latest'
    hostname: '${PROJECT_NAME}_db'
    container_name: '${PROJECT_NAME}_mysql'
    networks:
      - jefe-cli
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
  <PROJECT_NAME>_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${PROJECT_NAME}_phpmyadmin'
    networks:
      - jefe-cli
    environment:
      PMA_HOST: <PROJECT_NAME>_mysql
      VIRTUAL_HOST: 'phpmyadmin.${VHOST}'
    depends_on:
      - <PROJECT_NAME>_mysql
volumes:
  db_data: null
networks:
  jefe-cli:
    external:
      name: jefe-cli

